import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 18,
    color: '#222',
    textAlign: 'center',
    marginTop: 18,
  },
  cartContent: {
    flex: 1,
    paddingHorizontal: 8,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  itemImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: '#fff',
  },
  noImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: '#eee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  itemName: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#23272f',
    marginBottom: 2,
  },
  cantidad: {
    color: '#1976d2',
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 2,
  },
  trashBtn: {
    marginLeft: 10,
    padding: 4,
  },
  preciosContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 2,
  },
  precioTachado: {
    textDecorationLine: 'line-through',
    color: '#888',
    fontSize: 16,
    marginBottom: 2,
  },
  precioDescuento: {
    fontWeight: 'bold',
    color: 'red',
    fontSize: 18,
    marginTop: 2,
  },
  precioNormal: {
    fontWeight: 'bold',
    color: '#222',
    fontSize: 18,
    marginTop: 2,
  },
  resumenPago: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 18,
    marginTop: 18,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  resumenTitle: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#222',
    marginBottom: 10,
    textAlign: 'left',
  },
  resumenRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  resumenLabel: {
    color: '#444',
    fontSize: 16,
  },
  resumenValor: {
    color: '#23272f',
    fontWeight: 'bold',
    fontSize: 16,
  },
  resumenRowTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 8,
  },
  resumenLabelTotal: {
    color: '#1976d2',
    fontWeight: 'bold',
    fontSize: 18,
  },
  resumenValorTotal: {
    color: '#d32f2f',
    fontWeight: 'bold',
    fontSize: 18,
  },
  btnPedido: {
    backgroundColor: '#218838',
    borderRadius: 8,
    paddingVertical: 12,
    marginTop: 10,
    marginBottom: 6,
    alignItems: 'center',
  },
  btnPedidoText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
  },
  btnVolver: {
    backgroundColor: '#757575',
    borderRadius: 8,
    paddingVertical: 12,
    marginTop: 0,
    alignItems: 'center',
  },
  btnVolverText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
  },
});
