import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scroll: {
    flexGrow: 1,
    backgroundColor: '#f5f6fa',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 20,
  },
  container: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 22,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 30,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 18,
    color: '#000000FF',
    textAlign: 'center',
  },
  formGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
  },
  icon: {
    marginRight: 10,
    marginLeft: 2,
    width: 28,
    textAlign: 'center',
    color: '#444444',
  },
  input: {
    flex: 1,
    fontSize: 16,
    backgroundColor: '#f7f7f7',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    color: '#222',
  },
  eyeBtn: {
    position: 'absolute',
    right: 10,
    top: 18,
    padding: 2,
    zIndex: 2,
  },
  btn: {
    backgroundColor: '#000000FF',
    borderRadius: 12,
    paddingVertical: 12,
    marginTop: 10,
    marginBottom: 8,
    alignItems: 'center',
    alignSelf: 'center',
    minWidth: 180,
  },
  btnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  mensaje: {
    marginTop: 10,
    color: '#1976d2',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
  },
});
